-- Migrazione incrementale: attivitÃ  condivise. Non elimina dati esistenti.
create table public.area_activities (
 id uuid primary key default gen_random_uuid(),area_id uuid not null references public.areas(id) on delete cascade,title text not null check(char_length(btrim(title))>0),notes text,activity_type text not null check(activity_type in('task','reminder','deadline','appointment')),status text not null default 'open' check(status in('open','completed','cancelled')),priority text not null default 'normal' check(priority in('low','normal','high')),starts_at timestamptz,due_at timestamptz,is_all_day boolean not null default false,created_by_profile_id uuid references public.profiles(id) on delete set null,completed_by_profile_id uuid references public.profiles(id) on delete set null,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint area_activities_dates_check check(starts_at is null or due_at is null or due_at>=starts_at),constraint area_activities_completion_check check((status='completed' and completed_at is not null) or(status<>'completed' and completed_at is null and completed_by_profile_id is null)),unique(id,area_id));
create table public.activity_assignees (activity_id uuid not null,area_id uuid not null,profile_id uuid not null,assigned_at timestamptz not null default now(),assigned_by_profile_id uuid references public.profiles(id) on delete set null,primary key(activity_id,profile_id),foreign key(activity_id,area_id) references public.area_activities(id,area_id) on delete cascade,foreign key(area_id,profile_id) references public.area_memberships(area_id,profile_id) on delete cascade);
create index area_activities_open_due_idx on public.area_activities(area_id,status,due_at) where status='open';
create index area_activities_starts_idx on public.area_activities(area_id,starts_at) where starts_at is not null;
create index area_activities_created_idx on public.area_activities(area_id,created_at desc);
create index activity_assignees_profile_idx on public.activity_assignees(area_id,profile_id,activity_id);
alter table public.area_activities enable row level security; alter table public.activity_assignees enable row level security;
alter table public.area_activities no force row level security; alter table public.activity_assignees no force row level security;
create function public.current_area_activity_role(p_area_id uuid) returns table(profile_id uuid,role text) language sql security definer stable set search_path=public,pg_temp as $$select am.profile_id,am.role from public.area_memberships am join public.profiles p on p.id=am.profile_id where am.area_id=p_area_id and p.user_id=auth.uid() and am.role in('admin','member')$$;
create function public.set_area_activity_updated_at() returns trigger language plpgsql set search_path=public,pg_temp as $$begin new.updated_at=now();return new;end$$;
create trigger area_activities_set_updated_at before update on public.area_activities for each row execute function public.set_area_activity_updated_at();
-- Le sette RPC seguenti sono identiche alle definizioni canoniche in schema.sql;
-- mantenerle sincronizzate quando lo schema viene evoluto.
create function public.get_area_activities(p_area_id uuid,p_status text default null,p_activity_type text default null,p_assigned_to_me boolean default false,p_due_from timestamptz default null,p_due_to timestamptz default null) returns setof public.area_activities language plpgsql security definer set search_path=public,pg_temp as $$declare v uuid;begin select profile_id into v from public.current_area_activity_role(p_area_id);if v is null then raise exception 'permission denied';end if;return query select a.* from public.area_activities a where a.area_id=p_area_id and(p_status is null or a.status=p_status)and(p_activity_type is null or a.activity_type=p_activity_type)and(p_due_from is null or a.due_at>=p_due_from)and(p_due_to is null or a.due_at<=p_due_to)and(not p_assigned_to_me or exists(select 1 from public.activity_assignees x where x.activity_id=a.id and x.profile_id=v)or not exists(select 1 from public.activity_assignees x where x.activity_id=a.id));end$$;
create function public.get_area_activity(p_area_id uuid,p_activity_id uuid) returns public.area_activities language plpgsql security definer set search_path=public,pg_temp as $$declare r public.area_activities;begin if not exists(select 1 from public.current_area_activity_role(p_area_id))then raise exception 'permission denied';end if;select * into r from public.area_activities where id=p_activity_id and area_id=p_area_id;if not found then raise exception 'AttivitÃ  non trovata';end if;return r;end$$;
-- Le RPC di scrittura sono definite integralmente nello schema canonico e devono
-- essere applicate da questa stessa migrazione prima dell'uso in produzione.
-- Placeholder intenzionalmente non eseguibili: evita un deployment parziale.
create function public.create_area_activity(p_area_id uuid,p_title text,p_notes text,p_activity_type text,p_priority text,p_starts_at timestamptz,p_due_at timestamptz,p_is_all_day boolean,p_assignee_profile_ids uuid[] default '{}') returns uuid language plpgsql security definer set search_path=public,pg_temp as $$declare p uuid;r text;i uuid;v uuid[]:=coalesce(p_assignee_profile_ids,'{}');begin select profile_id,role into p,r from public.current_area_activity_role(p_area_id);if p is null then raise exception 'permission denied';end if;if btrim(coalesce(p_title,''))=''or p_activity_type not in('task','reminder','deadline','appointment')or p_priority not in('low','normal','high')or(p_starts_at is not null and p_due_at is not null and p_due_at<p_starts_at)then raise exception 'Dati attivitÃ  non validi';end if;if r='member'and exists(select 1 from unnest(v)x where x is distinct from p)then raise exception 'permission denied';end if;if exists(select 1 from unnest(v)x left join public.area_memberships m on m.area_id=p_area_id and m.profile_id=x where m.profile_id is null)then raise exception 'Assegnatario non appartenente all''Area';end if;insert into public.area_activities(area_id,title,notes,activity_type,priority,starts_at,due_at,is_all_day,created_by_profile_id)values(p_area_id,btrim(p_title),p_notes,p_activity_type,p_priority,p_starts_at,p_due_at,coalesce(p_is_all_day,false),p)returning id into i;insert into public.activity_assignees(activity_id,area_id,profile_id,assigned_by_profile_id)select i,p_area_id,x,p from(select distinct unnest(v)x)s;return i;end$$;
create function public.update_area_activity(p_area_id uuid,p_activity_id uuid,p_title text,p_notes text,p_activity_type text,p_priority text,p_starts_at timestamptz,p_due_at timestamptz,p_is_all_day boolean)returns void language plpgsql security definer set search_path=public,pg_temp as $$declare p uuid;r text;c uuid;begin select profile_id,role into p,r from public.current_area_activity_role(p_area_id);select created_by_profile_id into c from public.area_activities where id=p_activity_id and area_id=p_area_id;if p is null or not found or(r<>'admin'and c is distinct from p)then raise exception 'permission denied';end if;if btrim(coalesce(p_title,''))=''or p_activity_type not in('task','reminder','deadline','appointment')or p_priority not in('low','normal','high')or(p_starts_at is not null and p_due_at is not null and p_due_at<p_starts_at)then raise exception 'Dati attivitÃ  non validi';end if;update public.area_activities set title=btrim(p_title),notes=p_notes,activity_type=p_activity_type,priority=p_priority,starts_at=p_starts_at,due_at=p_due_at,is_all_day=coalesce(p_is_all_day,false)where id=p_activity_id and area_id=p_area_id;end$$;
create function public.set_area_activity_assignees(p_area_id uuid,p_activity_id uuid,p_assignee_profile_ids uuid[])returns void language plpgsql security definer set search_path=public,pg_temp as $$declare p uuid;r text;v uuid[]:=coalesce(p_assignee_profile_ids,'{}');begin select profile_id,role into p,r from public.current_area_activity_role(p_area_id);if r<>'admin'or not exists(select 1 from public.area_activities where id=p_activity_id and area_id=p_area_id)then raise exception 'permission denied';end if;if exists(select 1 from unnest(v)x left join public.area_memberships m on m.area_id=p_area_id and m.profile_id=x where m.profile_id is null)then raise exception 'Assegnatario non appartenente all''Area';end if;delete from public.activity_assignees where activity_id=p_activity_id and area_id=p_area_id;insert into public.activity_assignees(activity_id,area_id,profile_id,assigned_by_profile_id)select p_activity_id,p_area_id,x,p from(select distinct unnest(v)x)s;end$$;
create function public.set_area_activity_status(p_area_id uuid,p_activity_id uuid,p_status text)returns void language plpgsql security definer set search_path=public,pg_temp as $$declare p uuid;r text;begin select profile_id,role into p,r from public.current_area_activity_role(p_area_id);if p is null or p_status not in('open','completed','cancelled')or not exists(select 1 from public.area_activities where id=p_activity_id and area_id=p_area_id)or(r<>'admin'and(p_status<>'completed'or(exists(select 1 from public.activity_assignees where activity_id=p_activity_id)and not exists(select 1 from public.activity_assignees where activity_id=p_activity_id and profile_id=p))))then raise exception 'permission denied';end if;update public.area_activities set status=p_status,completed_at=case when p_status='completed'then now()else null end,completed_by_profile_id=case when p_status='completed'then p else null end where id=p_activity_id and area_id=p_area_id;end$$;
create function public.delete_area_activity(p_area_id uuid,p_activity_id uuid)returns void language plpgsql security definer set search_path=public,pg_temp as $$declare p uuid;r text;c uuid;s text;begin select profile_id,role into p,r from public.current_area_activity_role(p_area_id);select created_by_profile_id,status into c,s from public.area_activities where id=p_activity_id and area_id=p_area_id;if p is null or not found or(r<>'admin'and(c is distinct from p or s<>'open'))then raise exception 'permission denied';end if;delete from public.area_activities where id=p_activity_id and area_id=p_area_id;end$$;
revoke all on public.area_activities,public.activity_assignees from public,authenticated;
revoke all on function public.current_area_activity_role(uuid),public.set_area_activity_updated_at(),public.get_area_activities(uuid,text,text,boolean,timestamptz,timestamptz),public.get_area_activity(uuid,uuid),public.create_area_activity(uuid,text,text,text,text,timestamptz,timestamptz,boolean,uuid[]),public.update_area_activity(uuid,uuid,text,text,text,text,timestamptz,timestamptz,boolean),public.set_area_activity_assignees(uuid,uuid,uuid[]),public.set_area_activity_status(uuid,uuid,text),public.delete_area_activity(uuid,uuid) from public;
grant execute on function public.get_area_activities(uuid,text,text,boolean,timestamptz,timestamptz),public.get_area_activity(uuid,uuid),public.create_area_activity(uuid,text,text,text,text,timestamptz,timestamptz,boolean,uuid[]),public.update_area_activity(uuid,uuid,text,text,text,text,timestamptz,timestamptz,boolean),public.set_area_activity_assignees(uuid,uuid,uuid[]),public.set_area_activity_status(uuid,uuid,text),public.delete_area_activity(uuid,uuid) to authenticated;
