const supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
const form = document.getElementById('preferences-form'), message = document.getElementById('preferences-message'), organizationSection = document.getElementById('organization-settings'), organizationTitle = document.getElementById('organization-settings-title'), organizationNameForm = document.getElementById('organization-name-form'), organizationNameInput = document.getElementById('organization-name-input'), organizationNameSave = document.getElementById('organization-name-save-button'), organizationNameMessage = document.getElementById('organization-name-message');
const avatarImage = document.getElementById('organization-avatar-image'), avatarFallback = document.getElementById('organization-avatar-fallback'), avatarInput = document.getElementById('organization-avatar-file-input'), avatarUpload = document.getElementById('organization-avatar-upload-label'), avatarRemove = document.getElementById('organization-avatar-remove-button'), avatarMessage = document.getElementById('organization-avatar-message');
const coverPreview = document.getElementById('organization-cover-preview'), coverImage = document.getElementById('organization-cover-image'), coverInput = document.getElementById('organization-cover-file-input'), coverUpload = document.getElementById('organization-cover-upload-label'), coverRemove = document.getElementById('organization-cover-remove-button'), coverMessage = document.getElementById('organization-cover-message');
const allowedImageTypes = new Set(['image/jpeg', 'image/png', 'image/webp']);
let organization;
function initials(name) { return (name || 'O').trim().charAt(0).toLocaleUpperCase('it-IT') || 'O'; }
function showMessage(element, text, isError = false) { element.textContent = text; element.classList.toggle('is-error', isError); element.classList.toggle('is-success', Boolean(text) && !isError); }
function notifyOrganizationChanged() { window.dispatchEvent(new CustomEvent('familarea:organization-changed', { detail: { organization } })); }
function setBusy(input, upload, remove, busy, label) { input.disabled = busy; upload.classList.toggle('is-disabled', busy); remove.disabled = busy; if (label) upload.textContent = label; }
function renderIdentity() { organizationTitle.textContent = organization.name; organizationNameInput.value = organization.name; avatarFallback.textContent = initials(organization.name); }
function renderAvatarFallback() { avatarImage.hidden = true; avatarImage.removeAttribute('src'); avatarFallback.hidden = false; avatarUpload.textContent = organization.avatar_path ? 'Sostituisci immagine' : 'Carica immagine'; avatarRemove.hidden = !organization.avatar_path; }
async function renderAvatar() { if (!organization.avatar_path) { renderAvatarFallback(); return; } const { data, error } = await supabaseClient.storage.from('organization-avatars').createSignedUrl(organization.avatar_path, 3600); if (error || !data?.signedUrl) { renderAvatarFallback(); return; } avatarImage.src = `${data.signedUrl}${data.signedUrl.includes('?') ? '&' : '?'}v=${Date.now()}`; avatarImage.alt = `Immagine di ${organization.name}`; avatarImage.hidden = false; avatarFallback.hidden = true; avatarUpload.textContent = 'Sostituisci immagine'; avatarRemove.hidden = false; }
function renderCoverFallback() { coverPreview.hidden = true; coverImage.removeAttribute('src'); coverUpload.textContent = organization.dashboard_cover_path ? 'Sostituisci immagine' : 'Carica immagine'; coverRemove.hidden = !organization.dashboard_cover_path; }
async function renderCover() { if (!organization.dashboard_cover_path) { renderCoverFallback(); return; } const { data, error } = await supabaseClient.storage.from('organization-dashboard-covers').createSignedUrl(organization.dashboard_cover_path, 3600); if (error || !data?.signedUrl) { renderCoverFallback(); return; } coverImage.src = `${data.signedUrl}${data.signedUrl.includes('?') ? '&' : '?'}v=${Date.now()}`; coverPreview.hidden = false; coverUpload.textContent = 'Sostituisci immagine'; coverRemove.hidden = false; }
async function saveName(event) { event.preventDefault(); const name = organizationNameInput.value.trim(); if (!name) { showMessage(organizationNameMessage, 'Inserisci il nome dell’organizzazione.', true); return; } organizationNameSave.disabled = true; showMessage(organizationNameMessage, 'Salvataggio nome in corso...'); const { data, error } = await supabaseClient.rpc('update_my_organization_name', { p_name: name }); organizationNameSave.disabled = false; if (error || !data) { console.error('update_my_organization_name failed', error); showMessage(organizationNameMessage, 'Impossibile salvare il nome. Riprova.', true); return; } organization = data; renderIdentity(); await renderAvatar(); notifyOrganizationChanged(); showMessage(organizationNameMessage, 'Nome dell’organizzazione aggiornato.'); }
function imageConfig(kind) { return kind === 'avatar' ? { input: avatarInput, upload: avatarUpload, remove: avatarRemove, message: avatarMessage, bucket: 'organization-avatars', suffix: 'avatar', max: 2 * 1024 * 1024, property: 'avatar_path', rpc: 'update_my_organization_avatar', parameter: 'p_avatar_path', render: renderAvatar, label: 'Immagine' } : { input: coverInput, upload: coverUpload, remove: coverRemove, message: coverMessage, bucket: 'organization-dashboard-covers', suffix: 'cover', max: 5 * 1024 * 1024, property: 'dashboard_cover_path', rpc: 'update_my_organization_dashboard_cover', parameter: 'p_cover_path', render: renderCover, label: 'Copertina' }; }
async function uploadImage(kind) { const config = imageConfig(kind), file = config.input.files?.[0]; config.input.value = ''; if (!file) return; if (!allowedImageTypes.has(file.type)) { showMessage(config.message, 'Scegli un’immagine JPG, PNG o WebP.', true); return; } if (file.size > config.max) { showMessage(config.message, `L’immagine deve pesare al massimo ${config.max / 1048576} MB.`, true); return; } const path = `${organization.id}/${config.suffix}`; setBusy(config.input, config.upload, config.remove, true, 'Caricamento...'); showMessage(config.message, 'Caricamento immagine in corso...'); const { error: uploadError } = await supabaseClient.storage.from(config.bucket).upload(path, file, { upsert: true, contentType: file.type }); if (uploadError) { console.error('image upload failed', uploadError); setBusy(config.input, config.upload, config.remove, false); await config.render(); showMessage(config.message, 'Impossibile caricare l’immagine. Riprova.', true); return; } const { data, error } = await supabaseClient.rpc(config.rpc, { [config.parameter]: path }); setBusy(config.input, config.upload, config.remove, false); if (error || !data) { console.error(`${config.rpc} failed`, error); await config.render(); showMessage(config.message, 'Immagine caricata, ma non è stato possibile associarla all’organizzazione.', true); return; } organization = data; await config.render(); notifyOrganizationChanged(); showMessage(config.message, `${config.label} aggiornata.`); }
async function removeImage(kind) { const config = imageConfig(kind); const confirmed = await FamilAreaConfirm.confirm({ variant: 'standard', title: kind === 'avatar' ? 'Rimuovere l’immagine dell’organizzazione?' : 'Rimuovere l’immagine di copertina?', message: kind === 'avatar' ? 'Al suo posto verrà mostrata l’iniziale dell’organizzazione.' : 'La Dashboard tornerà al suo aspetto FamilArea originale.', confirmText: 'Rimuovi immagine' }); if (!confirmed) return; const path = organization[config.property]; setBusy(config.input, config.upload, config.remove, true, 'Rimozione...'); showMessage(config.message, 'Rimozione immagine in corso...'); if (path) { const { error } = await supabaseClient.storage.from(config.bucket).remove([path]); if (error) { console.error('image removal failed', error); setBusy(config.input, config.upload, config.remove, false); showMessage(config.message, 'Impossibile rimuovere l’immagine. Riprova.', true); return; } } const { data, error } = await supabaseClient.rpc(config.rpc, { [config.parameter]: null }); setBusy(config.input, config.upload, config.remove, false); if (error || !data) { console.error(`${config.rpc} failed`, error); showMessage(config.message, 'Immagine rimossa, ma non è stato possibile aggiornare l’organizzazione.', true); return; } organization = data; await config.render(); notifyOrganizationChanged(); showMessage(config.message, 'Immagine rimossa.'); }
async function load() { const { data: session } = await supabaseClient.auth.getSession(); if (!session.session) { location.href = 'login.html'; return; } const { data: account, error: accountError } = await supabaseClient.rpc('get_current_account'); if (accountError || !account) { message.textContent = 'Impossibile caricare le impostazioni dell’account.'; return; } form.hidden = true; if (account.account_type === 'personal') { message.innerHTML = 'Le informazioni personali sono disponibili nel tuo <a href="profilo.html">Profilo</a>.'; return; } const { data, error } = await supabaseClient.rpc('get_my_organization'); if (error || !data) { message.textContent = 'Impossibile caricare le impostazioni dell’organizzazione.'; return; } organization = data; message.textContent = 'Gestisci il nome, le immagini e le preferenze della tua organizzazione.'; renderIdentity(); organizationSection.hidden = false; await Promise.all([renderAvatar(), renderCover()]); }
organizationNameForm.addEventListener('submit', saveName); avatarInput.addEventListener('change', () => void uploadImage('avatar')); avatarRemove.addEventListener('click', () => void removeImage('avatar')); coverInput.addEventListener('change', () => void uploadImage('cover')); coverRemove.addEventListener('click', () => void removeImage('cover')); load();
