const deadlineDetailClient = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
const detailId = new URLSearchParams(window.location.search).get('deadline_id');
const detailMessage = document.getElementById('deadline-message'); const detailContent = document.getElementById('deadline-content');
const detailTitle = document.getElementById('deadline-title'); const detailSubtitle = document.getElementById('deadline-subtitle'); const detailStatus = document.getElementById('deadline-status'); const detailList = document.getElementById('deadline-details-list'); const occurrenceList = document.getElementById('deadline-occurrences-list');
const categoryLabels = { vehicle: 'Auto e veicoli', home: 'Casa', documents: 'Documenti', animals: 'Animali', contracts_subscriptions: 'Contratti e abbonamenti', other: 'Altro' };
function formatDate(value) { return value ? new Date(`${value}T00:00:00`).toLocaleDateString('it-IT') : '—'; }
function recurrenceLabel(months) { return ({ 1: 'Ogni mese', 6: 'Ogni 6 mesi', 12: 'Ogni anno', 24: 'Ogni 2 anni' })[Number(months)] || 'Non ripetere'; }
function reminderLabel(days) { return Number(days) === 0 ? 'Il giorno stesso' : `${days} giorni prima`; }
function memberName(member) { return `${member?.first_name || ''} ${member?.last_name || ''}`.trim() || (member?.member_type === 'pet' ? 'Animale domestico' : '—'); }
function occurrenceLabel(item, isNextFuture) { if (item.is_completed) return 'Fatto'; if (item.occurrence_state === 'overdue') return 'Scaduta'; if (item.occurrence_state === 'today') return 'Oggi'; if (item.occurrence_state === 'upcoming') return isNextFuture ? 'Prossima' : 'Futura'; return 'Non confermata'; }
let currentDeadline; let familyMembers = new Map();
function renderDetails(deadline) { detailTitle.textContent = deadline.title; detailSubtitle.textContent = deadline.reference || categoryLabels[deadline.category] || ''; detailStatus.textContent = deadline.status === 'terminated' ? 'Terminata' : 'Attiva'; detailStatus.className = `deadline-status is-${deadline.status}`; document.getElementById('edit-deadline').href = `nuova-scadenza.html?deadline_id=${encodeURIComponent(deadline.id)}`; document.getElementById('terminate-deadline').hidden = deadline.status !== 'active'; const details = [['Categoria', categoryLabels[deadline.category] || deadline.category], ['Riferimento', deadline.reference || '—'], ['Membro Famiglia', deadline.family_member_id ? memberName(familyMembers.get(deadline.family_member_id)) : 'Nessun membro'], ['Prima scadenza', formatDate(deadline.first_due_on)], ['Ricorrenza', recurrenceLabel(deadline.recurrence_months)], ['Promemoria', reminderLabel(deadline.reminder_days)], ['Stato', deadline.status === 'terminated' ? `Terminata il ${formatDate(deadline.terminated_on)}` : 'Attiva'], ['Note', deadline.notes || '—']]; detailList.replaceChildren(); details.forEach(([label, value]) => { const term = document.createElement('dt'); term.textContent = label; const description = document.createElement('dd'); description.textContent = value; detailList.append(term, description); }); }
function renderOccurrences(items) { occurrenceList.replaceChildren(); if (!items.length) { occurrenceList.textContent = 'Nessuna occorrenza nel periodo selezionato.'; return; } const today = new Date(new Date().toDateString()); const nextFuture = items.find((item) => !item.is_completed && new Date(`${item.occurrence_on}T00:00:00`) > today); items.forEach((item) => { const row = document.createElement('article'); row.className = `deadline-occurrence${item.is_completed ? ' deadline-occurrence-completed' : ''}`; const text = document.createElement('div'); const date = document.createElement('h3'); date.textContent = formatDate(item.occurrence_on); const state = document.createElement('span'); state.className = `deadline-occurrence-state is-${item.occurrence_state}`; state.textContent = occurrenceLabel(item, nextFuture?.occurrence_on === item.occurrence_on); text.append(date, state); row.appendChild(text); const pastOrToday = new Date(`${item.occurrence_on}T00:00:00`) <= today; if (pastOrToday) { const button = document.createElement('button'); button.type = 'button'; button.className = 'secondary-button'; button.textContent = item.is_completed ? 'Ripristina' : 'Segna come fatto'; button.addEventListener('click', () => updateCompletion(item, button)); row.appendChild(button); } occurrenceList.appendChild(row); }); }
async function updateCompletion(item, button) { button.disabled = true; detailMessage.textContent = 'Aggiornamento...'; const { error } = await deadlineDetailClient.rpc('set_my_deadline_occurrence_completed', { p_deadline_id: currentDeadline.id, p_occurrence_on: item.occurrence_on, p_completed: !item.is_completed }); if (error) { detailMessage.textContent = 'Non è stato possibile aggiornare questa occorrenza.'; button.disabled = false; return; } await loadDeadline(); }
async function loadDeadline() { if (!detailId) { detailMessage.textContent = 'Scadenza non specificata.'; return; } const [{ data: deadlineData, error }, memberResult] = await Promise.all([deadlineDetailClient.rpc('get_my_deadline', { p_deadline_id: detailId }), deadlineDetailClient.rpc('get_my_family_members')]); currentDeadline = deadlineData?.[0]; if (error || !currentDeadline) { detailMessage.textContent = 'Scadenza non trovata o non accessibile.'; detailContent.hidden = true; return; } familyMembers = new Map((memberResult.data || []).map((member) => [member.id, member])); const today = new Date(); today.setHours(0, 0, 0, 0); const from = new Date(today); from.setFullYear(from.getFullYear() - 1); const to = new Date(today); to.setFullYear(to.getFullYear() + 2); const { data: occurrences, error: occurrenceError } = await deadlineDetailClient.rpc('get_my_deadline_occurrences', { p_from: from.toISOString().slice(0, 10), p_to: to.toISOString().slice(0, 10) }); renderDetails(currentDeadline); renderOccurrences((occurrences || []).filter((item) => item.deadline_id === currentDeadline.id)); detailContent.hidden = false; detailMessage.textContent = occurrenceError ? 'Dettagli disponibili; non è stato possibile caricare tutte le occorrenze.' : ''; }
document.getElementById('terminate-deadline').addEventListener('click', async () => { if (!currentDeadline || !(await window.FamilAreaConfirm.confirm({ title: 'Terminare questa scadenza?', message: 'Non verranno generate nuove occorrenze future. Lo storico resterà disponibile.', confirmText: 'Termina scadenza' }))) return; detailMessage.textContent = 'Terminazione...'; const { error } = await deadlineDetailClient.rpc('terminate_my_deadline', { p_deadline_id: currentDeadline.id }); if (error) { detailMessage.textContent = 'Non è stato possibile terminare la scadenza.'; return; } await loadDeadline(); });
document.getElementById('delete-deadline').addEventListener('click', async () => { if (!currentDeadline || !(await window.FamilAreaConfirm.confirm({ variant: 'danger', title: 'Eliminare scadenza?', message: 'Eliminare definitivamente questa scadenza e il relativo storico?', confirmText: 'Elimina definitivamente' }))) return; detailMessage.textContent = 'Eliminazione...'; const { error } = await deadlineDetailClient.rpc('delete_my_deadline', { p_deadline_id: currentDeadline.id }); if (error) { detailMessage.textContent = 'Non è stato possibile eliminare la scadenza.'; return; } window.location.href = 'scadenze.html'; });
(async () => { const { data } = await deadlineDetailClient.auth.getSession(); if (!data.session) { window.location.href = 'login.html'; return; } await loadDeadline(); })();
