const deadlineDetailClient = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
const detailId = new URLSearchParams(window.location.search).get('deadline_id');
const detailMessage = document.getElementById('deadline-message'); const detailContent = document.getElementById('deadline-content');
const detailTitle = document.getElementById('deadline-title'); const detailSubtitle = document.getElementById('deadline-subtitle'); const detailStatus = document.getElementById('deadline-status'); const detailList = document.getElementById('deadline-details-list'); const occurrenceList = document.getElementById('deadline-occurrences-list');
const attachmentsList = document.getElementById('deadline-attachments-list'); const attachmentsEmpty = document.getElementById('deadline-attachments-empty'); const attachmentsMessage = document.getElementById('deadline-attachments-message'); const attachmentInput = document.getElementById('deadline-attachment-input');
const categoryLabels = { vehicle: 'Auto e veicoli', home: 'Casa', documents: 'Documenti', animals: 'Animali', contracts_subscriptions: 'Contratti e abbonamenti', other: 'Altro' };
function formatDate(value) { return value ? new Date(`${value}T00:00:00`).toLocaleDateString('it-IT') : '—'; }
function recurrenceLabel(months) { return ({ 1: 'Ogni mese', 6: 'Ogni 6 mesi', 12: 'Ogni anno', 24: 'Ogni 2 anni' })[Number(months)] || 'Non ripetere'; }
function reminderLabel(days) { return Number(days) === 0 ? 'Il giorno stesso' : `${days} giorni prima`; }
function memberName(member) { return `${member?.first_name || ''} ${member?.last_name || ''}`.trim() || (member?.member_type === 'pet' ? 'Animale domestico' : '—'); }
function occurrenceLabel(item, isNextFuture) { if (item.is_completed) return 'Fatto'; if (item.occurrence_state === 'overdue') return 'Scaduta'; if (item.occurrence_state === 'today') return 'Oggi'; if (item.occurrence_state === 'upcoming') return isNextFuture ? 'Prossima' : 'Futura'; return 'Non confermata'; }
let currentDeadline; let familyMembers = new Map();
const attachmentBucket = 'familarea-attachments'; const allowedAttachmentTypes = new Set(['application/pdf', 'image/jpeg', 'image/png', 'image/webp']); const maxAttachmentBytes = 2 * 1024 * 1024;
function formatAttachmentSize(bytes) { if (bytes >= 1024 * 1024) return `${(bytes / (1024 * 1024)).toLocaleString('it-IT', { maximumFractionDigits: 1 })} MB`; return `${Math.max(1, Math.round(bytes / 1024))} KB`; }
function formatAttachmentDate(value) { return value ? new Date(value).toLocaleDateString('it-IT') : ''; }
function clearAttachmentsMessage() { attachmentsMessage.textContent = ''; attachmentsMessage.className = 'deadline-attachments-message'; }
function setAttachmentsMessage(message, isError = true) { attachmentsMessage.textContent = message; attachmentsMessage.className = `deadline-attachments-message${isError ? ' is-error' : ''}`; }
function renderAttachments(items) { attachmentsList.replaceChildren(); attachmentsEmpty.hidden = items.length > 0; items.forEach((attachment) => { const row = document.createElement('article'); row.className = 'deadline-attachment'; const info = document.createElement('div'); info.className = 'deadline-attachment-info'; const name = document.createElement('strong'); name.textContent = attachment.original_filename; const meta = document.createElement('span'); meta.textContent = [attachment.mime_type.replace('application/', '').replace('image/', '').toUpperCase(), formatAttachmentSize(Number(attachment.byte_size)), formatAttachmentDate(attachment.created_at)].filter(Boolean).join(' · '); info.append(name, meta); const actions = document.createElement('div'); actions.className = 'deadline-attachment-actions'; const open = document.createElement('button'); open.type = 'button'; open.className = 'secondary-button'; open.textContent = 'Apri'; open.addEventListener('click', () => openAttachment(attachment, open)); const remove = document.createElement('button'); remove.type = 'button'; remove.className = 'secondary-button list-item-delete'; remove.textContent = 'Elimina'; remove.addEventListener('click', () => deleteAttachment(attachment, remove)); actions.append(open, remove); row.append(info, actions); attachmentsList.appendChild(row); }); }
async function loadAttachments() { if (!currentDeadline) return; const { data, error } = await deadlineDetailClient.rpc('get_my_attachments', { p_target_type: 'deadline', p_target_id: currentDeadline.id }); if (error) { attachmentsList.replaceChildren(); attachmentsEmpty.hidden = true; setAttachmentsMessage('Non è stato possibile caricare gli allegati.'); return; } clearAttachmentsMessage(); renderAttachments(data || []); }
async function openAttachment(attachment, button) { button.disabled = true; const tab = window.open('', '_blank'); const { data, error } = await deadlineDetailClient.rpc('get_my_attachment_download', { p_attachment_id: attachment.id }); const download = data?.[0]; if (error || !download) { if (tab) tab.close(); setAttachmentsMessage('Impossibile aprire l’allegato.'); button.disabled = false; return; } const { data: signed, error: signedError } = await deadlineDetailClient.storage.from(attachmentBucket).createSignedUrl(download.storage_path, 60); if (signedError || !signed?.signedUrl) { if (tab) tab.close(); setAttachmentsMessage('Impossibile aprire l’allegato.'); button.disabled = false; return; } if (tab) tab.location.href = signed.signedUrl; else window.open(signed.signedUrl, '_blank', 'noopener'); button.disabled = false; }
async function uploadAttachment(file) { if (!currentDeadline || !file) return; if (file.size > maxAttachmentBytes) { setAttachmentsMessage('Il file non può superare 2 MB.'); return; } if (!allowedAttachmentTypes.has(file.type)) { setAttachmentsMessage('Formato file non supportato.'); return; } attachmentInput.disabled = true; clearAttachmentsMessage(); const { data, error } = await deadlineDetailClient.rpc('create_my_attachment', { p_target_type: 'deadline', p_target_id: currentDeadline.id, p_original_filename: file.name, p_mime_type: file.type, p_byte_size: file.size }); const metadata = data?.[0]; if (error || !metadata) { setAttachmentsMessage('Impossibile caricare l’allegato.'); attachmentInput.disabled = false; return; } const { error: uploadError } = await deadlineDetailClient.storage.from(attachmentBucket).upload(metadata.storage_path, file, { contentType: file.type, upsert: false }); if (uploadError) { await deadlineDetailClient.rpc('delete_my_attachment', { p_attachment_id: metadata.id }); setAttachmentsMessage('Impossibile caricare l’allegato.'); attachmentInput.disabled = false; return; } attachmentInput.value = ''; attachmentInput.disabled = false; await loadAttachments(); }
async function deleteAttachment(attachment, button) { if (!(await window.FamilAreaConfirm.confirm({ variant: 'danger', title: 'Eliminare allegato?', message: `Eliminare definitivamente “${attachment.original_filename}”?`, confirmText: 'Elimina allegato' }))) return; button.disabled = true; clearAttachmentsMessage(); const { error: storageError } = await deadlineDetailClient.storage.from(attachmentBucket).remove([attachment.storage_path]); if (storageError) { setAttachmentsMessage('Impossibile eliminare l’allegato.'); button.disabled = false; return; } const { error } = await deadlineDetailClient.rpc('delete_my_attachment', { p_attachment_id: attachment.id }); if (error) { setAttachmentsMessage('Impossibile eliminare l’allegato.'); button.disabled = false; return; } await loadAttachments(); }
function renderDetails(deadline) { detailTitle.textContent = deadline.title; detailSubtitle.textContent = deadline.reference || categoryLabels[deadline.category] || ''; detailStatus.textContent = deadline.status === 'terminated' ? 'Terminata' : 'Attiva'; detailStatus.className = `deadline-status is-${deadline.status}`; document.getElementById('edit-deadline').href = `nuova-scadenza.html?deadline_id=${encodeURIComponent(deadline.id)}`; document.getElementById('terminate-deadline').hidden = deadline.status !== 'active'; const details = [['Categoria', categoryLabels[deadline.category] || deadline.category], ['Riferimento', deadline.reference || '—'], ['Membro Famiglia', deadline.family_member_id ? memberName(familyMembers.get(deadline.family_member_id)) : 'Nessun membro'], ['Prima scadenza', formatDate(deadline.first_due_on)], ['Ricorrenza', recurrenceLabel(deadline.recurrence_months)], ['Promemoria', reminderLabel(deadline.reminder_days)], ['Stato', deadline.status === 'terminated' ? `Terminata il ${formatDate(deadline.terminated_on)}` : 'Attiva'], ['Note', deadline.notes || '—']]; detailList.replaceChildren(); details.forEach(([label, value]) => { const term = document.createElement('dt'); term.textContent = label; const description = document.createElement('dd'); description.textContent = value; detailList.append(term, description); }); }
function renderOccurrences(items) { occurrenceList.replaceChildren(); if (!items.length) { occurrenceList.textContent = 'Nessuna occorrenza nel periodo selezionato.'; return; } const today = new Date(new Date().toDateString()); const nextFuture = items.find((item) => !item.is_completed && new Date(`${item.occurrence_on}T00:00:00`) > today); items.forEach((item) => { const row = document.createElement('article'); row.className = `deadline-occurrence${item.is_completed ? ' deadline-occurrence-completed' : ''}`; const text = document.createElement('div'); const date = document.createElement('h3'); date.textContent = formatDate(item.occurrence_on); const state = document.createElement('span'); state.className = `deadline-occurrence-state is-${item.occurrence_state}`; state.textContent = occurrenceLabel(item, nextFuture?.occurrence_on === item.occurrence_on); text.append(date, state); row.appendChild(text); const pastOrToday = new Date(`${item.occurrence_on}T00:00:00`) <= today; if (pastOrToday) { const button = document.createElement('button'); button.type = 'button'; button.className = 'secondary-button'; button.textContent = item.is_completed ? 'Ripristina' : 'Segna come fatto'; button.addEventListener('click', () => updateCompletion(item, button)); row.appendChild(button); } occurrenceList.appendChild(row); }); }
async function updateCompletion(item, button) { button.disabled = true; detailMessage.textContent = 'Aggiornamento...'; const { error } = await deadlineDetailClient.rpc('set_my_deadline_occurrence_completed', { p_deadline_id: currentDeadline.id, p_occurrence_on: item.occurrence_on, p_completed: !item.is_completed }); if (error) { detailMessage.textContent = 'Non è stato possibile aggiornare questa occorrenza.'; button.disabled = false; return; } await loadDeadline(); }
async function loadDeadline() { if (!detailId) { detailMessage.textContent = 'Scadenza non specificata.'; return; } const [{ data: deadlineData, error }, memberResult] = await Promise.all([deadlineDetailClient.rpc('get_my_deadline', { p_deadline_id: detailId }), deadlineDetailClient.rpc('get_my_family_members')]); currentDeadline = deadlineData?.[0]; if (error || !currentDeadline) { detailMessage.textContent = 'Scadenza non trovata o non accessibile.'; detailContent.hidden = true; return; } familyMembers = new Map((memberResult.data || []).map((member) => [member.id, member])); const today = new Date(); today.setHours(0, 0, 0, 0); const from = new Date(today); from.setFullYear(from.getFullYear() - 1); const to = new Date(today); to.setFullYear(to.getFullYear() + 2); const { data: occurrences, error: occurrenceError } = await deadlineDetailClient.rpc('get_my_deadline_occurrences', { p_from: from.toISOString().slice(0, 10), p_to: to.toISOString().slice(0, 10) }); renderDetails(currentDeadline); renderOccurrences((occurrences || []).filter((item) => item.deadline_id === currentDeadline.id)); detailContent.hidden = false; detailMessage.textContent = occurrenceError ? 'Dettagli disponibili; non è stato possibile caricare tutte le occorrenze.' : ''; await loadAttachments(); }
document.getElementById('terminate-deadline').addEventListener('click', async () => { if (!currentDeadline || !(await window.FamilAreaConfirm.confirm({ title: 'Terminare questa scadenza?', message: 'Non verranno generate nuove occorrenze future. Lo storico resterà disponibile.', confirmText: 'Termina scadenza' }))) return; detailMessage.textContent = 'Terminazione...'; const { error } = await deadlineDetailClient.rpc('terminate_my_deadline', { p_deadline_id: currentDeadline.id }); if (error) { detailMessage.textContent = 'Non è stato possibile terminare la scadenza.'; return; } await loadDeadline(); });
document.getElementById('delete-deadline').addEventListener('click', async () => { if (!currentDeadline || !(await window.FamilAreaConfirm.confirm({ variant: 'danger', title: 'Eliminare scadenza?', message: 'Eliminare definitivamente questa scadenza e il relativo storico?', confirmText: 'Elimina definitivamente' }))) return; detailMessage.textContent = 'Eliminazione...'; const { error } = await deadlineDetailClient.rpc('delete_my_deadline', { p_deadline_id: currentDeadline.id }); if (error) { detailMessage.textContent = 'Non è stato possibile eliminare la scadenza.'; return; } window.location.href = 'scadenze.html'; });
attachmentInput.addEventListener('change', () => uploadAttachment(attachmentInput.files?.[0]));
(async () => { const { data } = await deadlineDetailClient.auth.getSession(); if (!data.session) { window.location.href = 'login.html'; return; } await loadDeadline(); })();
