-- FamilArea next API. LOCAL DESIGN ONLY: run after familarea_baseline.sql.
-- All client-facing access is RPC-only. Tables have RLS enabled and no client grants.
begin;

create function public.require_area_read(p_area_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$
begin
 if not (public.is_area_owner(p_area_id) or public.is_area_member(p_area_id)) then raise exception 'permission denied'; end if;
end $$;
create function public.require_area_manage(p_area_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ begin if not public.can_manage_area(p_area_id) then raise exception 'permission denied'; end if; end $$;
create function public.area_scope(p_area_id uuid) returns table(owner_account_id uuid, area_id uuid) language sql security definer stable set search_path=public,pg_temp as $$ select null::uuid,a.id from public.areas a where a.id=p_area_id $$;
create function public.current_personal_profile_or_null() returns uuid language sql security definer stable set search_path=public,pg_temp as $$ select p.id from public.profiles p join public.accounts a on a.id=p.account_id where a.auth_user_id=auth.uid() and a.account_type='personal' $$;

create function public.get_current_account() returns jsonb language plpgsql security definer stable set search_path=public,pg_temp as $$
declare v_account public.accounts%rowtype; v_profile public.profiles%rowtype; v_org public.organizations%rowtype;
begin
 select * into v_account from public.accounts a where a.auth_user_id=auth.uid(); if not found then raise exception 'permission denied'; end if;
 if v_account.account_type='personal' then select * into v_profile from public.profiles p where p.account_id=v_account.id; return jsonb_build_object('account_id',v_account.id,'account_type','personal','profile_id',v_profile.id,'display_name',trim(concat_ws(' ',v_profile.first_name,v_profile.last_name)));
 end if;
 select * into v_org from public.organizations o where o.account_id=v_account.id; return jsonb_build_object('account_id',v_account.id,'account_type','organization','organization_id',v_org.id,'display_name',v_org.name,'status',v_org.status);
end $$;
create function public.get_my_profile() returns jsonb language sql security definer stable set search_path=public,pg_temp as $$ select to_jsonb(p) - 'account_id' from public.profiles p where p.id=public.require_personal_profile() $$;
create function public.update_my_profile(p_first_name text,p_last_name text default null,p_birth_date date default null,p_avatar_path text default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.profiles%rowtype; begin update public.profiles set first_name=nullif(btrim(p_first_name),''),last_name=nullif(btrim(p_last_name),''),birth_date=p_birth_date,avatar_path=p_avatar_path where id=public.require_personal_profile() returning * into v; if v.id is null then raise exception 'invalid profile'; end if; return to_jsonb(v)-'account_id'; end $$;
create function public.get_my_organization() returns jsonb language sql security definer stable set search_path=public,pg_temp as $$ select to_jsonb(o)-'account_id' from public.organizations o where o.id=public.current_organization() $$;
create function public.update_my_organization(p_name text,p_organization_type text,p_description text default null,p_contact_name text default null,p_contact_email text default null,p_contact_phone text default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.organizations%rowtype; begin update public.organizations set name=nullif(btrim(p_name),''),organization_type=nullif(btrim(p_organization_type),''),description=nullif(btrim(p_description),''),contact_name=nullif(btrim(p_contact_name),''),contact_email=nullif(lower(btrim(p_contact_email)),''),contact_phone=nullif(btrim(p_contact_phone),'') where id=public.current_organization() returning * into v; if v.id is null then raise exception 'invalid organization'; end if; return to_jsonb(v)-'account_id'; end $$;

create function public.create_area(p_name text,p_area_type text,p_description text default null) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare v uuid:=public.require_current_account(); begin insert into public.areas(owner_account_id,created_by_account_id,name,area_type,description) values(v,v,nullif(btrim(p_name),''),nullif(btrim(p_area_type),''),nullif(btrim(p_description),'')) returning id into v; return v; end $$;
create function public.get_my_areas() returns setof jsonb language sql security definer stable set search_path=public,pg_temp as $$ select jsonb_build_object('id',a.id,'name',a.name,'area_type',a.area_type,'description',a.description,'role',case when a.owner_account_id=public.current_account_id() then 'owner' else am.role::text end) from public.areas a left join public.area_memberships am on am.area_id=a.id and am.profile_id=public.current_personal_profile_or_null() where a.owner_account_id=public.current_account_id() or am.profile_id is not null order by a.name $$;
create function public.get_area(p_area_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.areas%rowtype; begin perform public.require_area_read(p_area_id); select * into v from public.areas where id=p_area_id; return to_jsonb(v); end $$;
create function public.update_area(p_area_id uuid,p_name text,p_area_type text,p_description text default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.areas%rowtype; begin perform public.require_area_manage(p_area_id); update public.areas set name=nullif(btrim(p_name),''),area_type=nullif(btrim(p_area_type),''),description=nullif(btrim(p_description),'') where id=p_area_id returning * into v; return to_jsonb(v); end $$;
create function public.delete_area(p_area_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ begin if not public.is_area_owner(p_area_id) then raise exception 'permission denied'; end if; delete from public.areas where id=p_area_id; end $$;
create function public.get_area_members(p_area_id uuid) returns setof jsonb language plpgsql security definer set search_path=public,pg_temp as $$ begin perform public.require_area_read(p_area_id); return query select jsonb_build_object('profile_id',p.id,'first_name',p.first_name,'last_name',p.last_name,'role',am.role) from public.area_memberships am join public.profiles p on p.id=am.profile_id where am.area_id=p_area_id order by p.first_name,p.last_name; end $$;
create function public.add_area_member(p_area_id uuid,p_profile_id uuid,p_role public.area_role default 'member') returns void language plpgsql security definer set search_path=public,pg_temp as $$ begin perform public.require_area_manage(p_area_id); if not exists(select 1 from public.profiles p where p.id=p_profile_id and p.account_id is null) then raise exception 'only managed profiles may be added directly'; end if; insert into public.area_memberships(area_id,profile_id,role,added_by_account_id) values(p_area_id,p_profile_id,p_role,public.require_current_account()) on conflict(area_id,profile_id) do update set role=excluded.role; end $$;
create function public.remove_area_member(p_area_id uuid,p_profile_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ begin perform public.require_area_manage(p_area_id); delete from public.area_memberships where area_id=p_area_id and profile_id=p_profile_id; end $$;

create function public.can_read_activity(p_id uuid) returns boolean language sql security definer stable set search_path=public,pg_temp as $$ select exists(select 1 from public.activities x where x.id=p_id and (x.owner_account_id=public.current_account_id() or (x.area_id is not null and (public.is_area_owner(x.area_id) or public.is_area_member(x.area_id))))) $$;
drop function if exists public.create_activity(text,text,uuid,timestamptz,timestamptz,boolean,public.priority_level,jsonb);
create function public.create_activity(p_title text,p_description text default null,p_area_id uuid default null,p_starts_at timestamptz default null,p_due_at timestamptz default null,p_is_all_day boolean default false,p_priority public.priority_level default 'normal',p_recurrence jsonb default '{}'::jsonb,p_activity_type text default 'task') returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare v_owner uuid; v_id uuid; begin if p_area_id is null then v_owner:=public.require_current_account(); else perform public.require_area_manage(p_area_id); end if; insert into public.activities(owner_account_id,area_id,title,description,activity_type,starts_at,due_at,is_all_day,priority,recurrence_frequency,recurrence_interval,recurrence_weekdays,recurrence_until,recurrence_timezone,created_by_account_id) values(v_owner,p_area_id,nullif(btrim(p_title),''),nullif(btrim(p_description),''),coalesce(nullif(btrim(p_activity_type),''),'task'),p_starts_at,p_due_at,coalesce(p_is_all_day,false),coalesce(p_priority,'normal'),nullif(p_recurrence->>'frequency',''),nullif(p_recurrence->>'interval','')::smallint,array(select jsonb_array_elements_text(coalesce(p_recurrence->'weekdays','[]'))::smallint),nullif(p_recurrence->>'until','')::date,nullif(p_recurrence->>'timezone',''),public.require_current_account()) returning id into v_id; return v_id; end $$;
create function public.get_activity(p_activity_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.activities%rowtype; begin if not public.can_read_activity(p_activity_id) then raise exception 'permission denied'; end if; select * into v from public.activities where id=p_activity_id; return to_jsonb(v); end $$;
create function public.get_visible_activities() returns setof jsonb language sql security definer stable set search_path=public,pg_temp as $$ select to_jsonb(x) from public.activities x where x.owner_account_id=public.current_account_id() or (x.area_id is not null and (public.is_area_owner(x.area_id) or public.is_area_member(x.area_id))) order by coalesce(x.due_at,x.starts_at),x.created_at $$;
create function public.get_activity_assignees(p_activity_id uuid) returns setof jsonb language plpgsql security definer stable set search_path=public,pg_temp as $$ begin if not public.can_read_activity(p_activity_id) then raise exception 'permission denied'; end if; return query select jsonb_build_object('profile_id',p.id,'first_name',p.first_name,'last_name',p.last_name) from public.activity_assignees aa join public.profiles p on p.id=aa.profile_id where aa.activity_id=p_activity_id order by p.first_name,p.last_name; end $$;
drop function if exists public.update_activity(uuid,text,text,timestamptz,timestamptz,boolean,public.priority_level,jsonb);
create function public.update_activity(p_activity_id uuid,p_title text,p_description text default null,p_starts_at timestamptz default null,p_due_at timestamptz default null,p_is_all_day boolean default false,p_priority public.priority_level default 'normal',p_recurrence jsonb default '{}'::jsonb,p_activity_type text default 'task') returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.activities%rowtype; begin select * into v from public.activities where id=p_activity_id; if not found or (v.owner_account_id is not null and v.owner_account_id<>public.require_current_account()) or (v.area_id is not null and not public.can_manage_area(v.area_id)) then raise exception 'permission denied'; end if; update public.activities set title=nullif(btrim(p_title),''),description=nullif(btrim(p_description),''),activity_type=coalesce(nullif(btrim(p_activity_type),''),'task'),starts_at=p_starts_at,due_at=p_due_at,is_all_day=coalesce(p_is_all_day,false),priority=coalesce(p_priority,'normal'),recurrence_frequency=nullif(p_recurrence->>'frequency',''),recurrence_interval=nullif(p_recurrence->>'interval','')::smallint,recurrence_weekdays=array(select jsonb_array_elements_text(coalesce(p_recurrence->'weekdays','[]'))::smallint),recurrence_until=nullif(p_recurrence->>'until','')::date,recurrence_timezone=nullif(p_recurrence->>'timezone','') where id=p_activity_id returning * into v; return to_jsonb(v); end $$;
create function public.set_activity_status(p_activity_id uuid,p_status public.activity_status) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.activities%rowtype; begin select * into v from public.activities where id=p_activity_id; if not found or (v.owner_account_id is not null and v.owner_account_id<>public.require_current_account()) or (v.area_id is not null and not public.can_manage_area(v.area_id)) then raise exception 'permission denied'; end if; update public.activities set status=p_status,completed_by_account_id=case when p_status='completed' then public.require_current_account() else null end,completed_at=case when p_status='completed' then now() else null end where id=p_activity_id; end $$;
create function public.delete_activity(p_activity_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.activities%rowtype; begin select * into v from public.activities where id=p_activity_id; if not found or (v.owner_account_id is not null and v.owner_account_id<>public.require_current_account()) or (v.area_id is not null and not public.can_manage_area(v.area_id)) then raise exception 'permission denied'; end if; delete from public.activities where id=p_activity_id; end $$;
create function public.set_activity_assignees(p_activity_id uuid,p_profile_ids uuid[]) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v_area uuid; begin select area_id into v_area from public.activities where id=p_activity_id; if v_area is null or not public.can_manage_area(v_area) then raise exception 'permission denied'; end if; if exists(select 1 from unnest(coalesce(p_profile_ids,'{}')) x(id) where not exists(select 1 from public.area_memberships am where am.area_id=v_area and am.profile_id=x.id)) then raise exception 'invalid assignee'; end if; delete from public.activity_assignees where activity_id=p_activity_id; insert into public.activity_assignees(activity_id,profile_id,assigned_by_account_id) select p_activity_id,x,public.require_current_account() from unnest(coalesce(p_profile_ids,'{}')) x; end $$;

create function public.can_read_event(p_id uuid) returns boolean language sql security definer stable set search_path=public,pg_temp as $$ select exists(select 1 from public.events x where x.id=p_id and (x.owner_account_id=public.current_account_id() or (x.area_id is not null and (public.is_area_owner(x.area_id) or public.is_area_member(x.area_id))))) $$;
create function public.create_event(p_title text,p_starts_at timestamptz,p_ends_at timestamptz default null,p_description text default null,p_area_id uuid default null,p_is_all_day boolean default false,p_location text default null,p_recurrence jsonb default '{}'::jsonb) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare v_owner uuid; v_id uuid; begin if p_area_id is null then v_owner:=public.require_current_account(); else perform public.require_area_manage(p_area_id); end if; insert into public.events(owner_account_id,area_id,title,description,starts_at,ends_at,is_all_day,location,recurrence_frequency,recurrence_until,created_by_account_id) values(v_owner,p_area_id,nullif(btrim(p_title),''),nullif(btrim(p_description),''),p_starts_at,p_ends_at,coalesce(p_is_all_day,false),nullif(btrim(p_location),''),nullif(p_recurrence->>'frequency',''),nullif(p_recurrence->>'until','')::date,public.require_current_account()) returning id into v_id; return v_id; end $$;
create function public.get_event(p_event_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ begin if not public.can_read_event(p_event_id) then raise exception 'permission denied'; end if; return (select to_jsonb(e) from public.events e where e.id=p_event_id); end $$;
create function public.get_visible_events() returns setof jsonb language sql security definer stable set search_path=public,pg_temp as $$ select to_jsonb(e) from public.events e where e.owner_account_id=public.current_account_id() or (e.area_id is not null and (public.is_area_owner(e.area_id) or public.is_area_member(e.area_id))) order by e.starts_at $$;
create function public.update_event(p_event_id uuid,p_title text,p_starts_at timestamptz,p_ends_at timestamptz default null,p_description text default null,p_is_all_day boolean default false,p_location text default null,p_recurrence jsonb default '{}'::jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.events%rowtype; begin select * into v from public.events where id=p_event_id; if not found or (v.owner_account_id is not null and v.owner_account_id<>public.require_current_account()) or (v.area_id is not null and not public.can_manage_area(v.area_id)) then raise exception 'permission denied'; end if; update public.events set title=nullif(btrim(p_title),''),description=nullif(btrim(p_description),''),starts_at=p_starts_at,ends_at=p_ends_at,is_all_day=coalesce(p_is_all_day,false),location=nullif(btrim(p_location),''),recurrence_frequency=nullif(p_recurrence->>'frequency',''),recurrence_until=nullif(p_recurrence->>'until','')::date where id=p_event_id returning * into v; return to_jsonb(v); end $$;
create function public.delete_event(p_event_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.events%rowtype; begin select * into v from public.events where id=p_event_id; if not found or (v.owner_account_id is not null and v.owner_account_id<>public.require_current_account()) or (v.area_id is not null and not public.can_manage_area(v.area_id)) then raise exception 'permission denied'; end if; delete from public.events where id=p_event_id; end $$;
create function public.set_event_participants(p_event_id uuid,p_profile_ids uuid[]) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v_area uuid; begin select area_id into v_area from public.events where id=p_event_id; if v_area is null or not public.can_manage_area(v_area) then raise exception 'permission denied'; end if; if exists(select 1 from unnest(coalesce(p_profile_ids,'{}')) x(id) where not exists(select 1 from public.area_memberships am where am.area_id=v_area and am.profile_id=x.id)) then raise exception 'invalid participant'; end if; delete from public.event_participants where event_id=p_event_id; insert into public.event_participants(event_id,profile_id) select p_event_id,x from unnest(coalesce(p_profile_ids,'{}')) x; end $$;
create function public.get_event_participants(p_event_id uuid) returns setof jsonb language plpgsql security definer stable set search_path=public,pg_temp as $$ begin if not public.can_read_event(p_event_id) then raise exception 'permission denied'; end if; return query select jsonb_build_object('profile_id',p.id,'first_name',p.first_name,'last_name',p.last_name,'status',ep.status) from public.event_participants ep join public.profiles p on p.id=ep.profile_id where ep.event_id=p_event_id order by p.first_name,p.last_name; end $$;
create function public.set_event_status(p_event_id uuid,p_status text) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.events%rowtype; begin select * into v from public.events where id=p_event_id; if not found or (v.owner_account_id is not null and v.owner_account_id<>public.require_current_account()) or (v.area_id is not null and not public.can_manage_area(v.area_id)) then raise exception 'permission denied'; end if; update public.events set status=nullif(btrim(p_status),'') where id=p_event_id; end $$;

create function public.create_list(p_title text,p_description text default null,p_area_id uuid default null) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare v_owner uuid; v_id uuid; begin if p_area_id is null then v_owner:=public.require_current_account(); else perform public.require_area_manage(p_area_id); end if; insert into public.lists(owner_account_id,area_id,title,description,created_by_account_id) values(v_owner,p_area_id,nullif(btrim(p_title),''),nullif(btrim(p_description),''),public.require_current_account()) returning id into v_id; return v_id; end $$;
create function public.get_list(p_list_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ begin if not exists(select 1 from public.lists l where l.id=p_list_id and (l.owner_account_id=public.current_account_id() or (l.area_id is not null and (public.is_area_owner(l.area_id) or public.is_area_member(l.area_id))))) then raise exception 'permission denied'; end if; return (select jsonb_build_object('list',to_jsonb(l),'items',coalesce((select jsonb_agg(to_jsonb(i) order by i.position,i.created_at) from public.list_items i where i.list_id=l.id),'[]'::jsonb)) from public.lists l where l.id=p_list_id); end $$;
create function public.get_visible_lists() returns setof jsonb language sql security definer stable set search_path=public,pg_temp as $$ select to_jsonb(l) from public.lists l where l.owner_account_id=public.current_account_id() or (l.area_id is not null and (public.is_area_owner(l.area_id) or public.is_area_member(l.area_id))) order by l.updated_at desc $$;
create function public.update_list(p_list_id uuid,p_title text,p_description text default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.lists%rowtype; begin select * into v from public.lists where id=p_list_id; if not found or (v.owner_account_id is not null and v.owner_account_id<>public.require_current_account()) or (v.area_id is not null and not public.can_manage_area(v.area_id)) then raise exception 'permission denied'; end if; update public.lists set title=nullif(btrim(p_title),''),description=nullif(btrim(p_description),'') where id=p_list_id returning * into v; return to_jsonb(v); end $$;
create function public.delete_list(p_list_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ begin perform public.update_list(p_list_id,(select title from public.lists where id=p_list_id),(select description from public.lists where id=p_list_id)); delete from public.lists where id=p_list_id; end $$;
create function public.create_list_item(p_list_id uuid,p_text text,p_position integer default 0) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare v uuid; begin perform public.update_list(p_list_id,(select title from public.lists where id=p_list_id),(select description from public.lists where id=p_list_id)); insert into public.list_items(list_id,text,position) values(p_list_id,nullif(btrim(p_text),''),p_position) returning id into v; return v; end $$;
create function public.update_list_item(p_item_id uuid,p_text text,p_position integer,p_status text default 'open') returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.list_items%rowtype; begin select i.* into v from public.list_items i join public.lists l on l.id=i.list_id where i.id=p_item_id; perform public.update_list(v.list_id,(select title from public.lists where id=v.list_id),(select description from public.lists where id=v.list_id)); update public.list_items set text=nullif(btrim(p_text),''),position=p_position,status=p_status where id=p_item_id returning * into v; return to_jsonb(v); end $$;
create function public.delete_list_item(p_item_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v uuid; begin select list_id into v from public.list_items where id=p_item_id; perform public.update_list(v,(select title from public.lists where id=v),(select description from public.lists where id=v)); delete from public.list_items where id=p_item_id; end $$;

create function public.create_deadline(p_title text,p_category text,p_first_due_on date,p_recurrence_months smallint default null,p_reminder_days smallint default 30,p_notes text default null,p_family_member_id uuid default null) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare v_account uuid:=public.require_current_account(); v_id uuid; begin if p_family_member_id is not null and not exists(select 1 from public.family_members fm join public.families f on f.id=fm.family_id where fm.id=p_family_member_id and f.owner_account_id=v_account and (select account_type from public.accounts where id=v_account)='personal') then raise exception 'invalid family member'; end if; insert into public.deadlines(owner_account_id,title,category,first_due_on,recurrence_months,reminder_days,notes,family_member_id) values(v_account,nullif(btrim(p_title),''),nullif(btrim(p_category),''),p_first_due_on,p_recurrence_months,coalesce(p_reminder_days,30),nullif(btrim(p_notes),''),p_family_member_id) returning id into v_id; return v_id; end $$;
create function public.get_deadline(p_deadline_id uuid) returns jsonb language sql security definer stable set search_path=public,pg_temp as $$ select to_jsonb(d) from public.deadlines d where d.id=p_deadline_id and d.owner_account_id=public.require_current_account() $$;
create function public.get_my_deadlines() returns setof jsonb language sql security definer stable set search_path=public,pg_temp as $$ select to_jsonb(d) from public.deadlines d where d.owner_account_id=public.require_current_account() order by d.first_due_on $$;
create function public.update_deadline(p_deadline_id uuid,p_title text,p_category text,p_first_due_on date,p_recurrence_months smallint default null,p_reminder_days smallint default 30,p_notes text default null,p_family_member_id uuid default null,p_status text default 'active') returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.deadlines%rowtype; begin if p_family_member_id is not null and not exists(select 1 from public.family_members fm join public.families f on f.id=fm.family_id where fm.id=p_family_member_id and f.owner_account_id=public.require_current_account()) then raise exception 'invalid family member'; end if; update public.deadlines set title=nullif(btrim(p_title),''),category=nullif(btrim(p_category),''),first_due_on=p_first_due_on,recurrence_months=p_recurrence_months,reminder_days=coalesce(p_reminder_days,30),notes=nullif(btrim(p_notes),''),family_member_id=p_family_member_id,status=p_status where id=p_deadline_id and owner_account_id=public.require_current_account() returning * into v; if not found then raise exception 'permission denied'; end if; return to_jsonb(v); end $$;
create function public.delete_deadline(p_deadline_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ begin delete from public.deadlines where id=p_deadline_id and owner_account_id=public.require_current_account(); if not found then raise exception 'permission denied'; end if; end $$;
create function public.get_deadline_occurrences(p_from date,p_to date) returns setof jsonb language sql security definer stable set search_path=public,pg_temp as $$ select jsonb_build_object('deadline_id',d.id,'title',d.title,'occurrence_on',o.occurrence_on,'completed',c.deadline_id is not null) from public.deadlines d cross join lateral generate_series(d.first_due_on,least(coalesce(d.terminated_on,p_to),p_to),make_interval(months=>coalesce(d.recurrence_months,1200))) o(occurrence_on) left join public.deadline_occurrence_completions c on c.deadline_id=d.id and c.occurrence_on=o.occurrence_on where d.owner_account_id=public.require_current_account() and d.status='active' and o.occurrence_on between p_from and p_to $$;
create function public.complete_deadline_occurrence(p_deadline_id uuid,p_occurrence_on date,p_completed boolean default true) returns void language plpgsql security definer set search_path=public,pg_temp as $$ begin if not exists(select 1 from public.deadlines d where d.id=p_deadline_id and d.owner_account_id=public.require_current_account()) then raise exception 'permission denied'; end if; if p_completed then insert into public.deadline_occurrence_completions(deadline_id,occurrence_on,completed_by_account_id) values(p_deadline_id,p_occurrence_on,public.require_current_account()) on conflict(deadline_id,occurrence_on) do nothing; else delete from public.deadline_occurrence_completions where deadline_id=p_deadline_id and occurrence_on=p_occurrence_on; end if; end $$;

create function public.create_contact(p_first_name text,p_last_name text default null,p_birth_date date default null) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare v uuid; begin insert into public.contacts(owner_account_id,first_name,last_name,birth_date) values(public.require_current_account(),nullif(btrim(p_first_name),''),nullif(btrim(p_last_name),''),p_birth_date) returning id into v; return v; end $$;
create function public.get_contact(p_contact_id uuid) returns jsonb language sql security definer stable set search_path=public,pg_temp as $$ select jsonb_build_object('contact',to_jsonb(c),'methods',coalesce((select jsonb_agg(to_jsonb(m)) from public.contact_methods m where m.contact_id=c.id),'[]'::jsonb)) from public.contacts c where c.id=p_contact_id and c.owner_account_id=public.require_current_account() $$;
create function public.get_my_contacts() returns setof jsonb language sql security definer stable set search_path=public,pg_temp as $$ select to_jsonb(c) from public.contacts c where c.owner_account_id=public.require_current_account() order by c.first_name,c.last_name $$;
create function public.update_contact(p_contact_id uuid,p_first_name text,p_last_name text default null,p_birth_date date default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.contacts%rowtype; begin update public.contacts set first_name=nullif(btrim(p_first_name),''),last_name=nullif(btrim(p_last_name),''),birth_date=p_birth_date where id=p_contact_id and owner_account_id=public.require_current_account() returning * into v; if not found then raise exception 'permission denied'; end if; return to_jsonb(v); end $$;
create function public.delete_contact(p_contact_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ begin delete from public.contacts where id=p_contact_id and owner_account_id=public.require_current_account(); if not found then raise exception 'permission denied'; end if; end $$;
create function public.replace_contact_methods(p_contact_id uuid,p_methods jsonb) returns void language plpgsql security definer set search_path=public,pg_temp as $$ begin if not exists(select 1 from public.contacts c where c.id=p_contact_id and c.owner_account_id=public.require_current_account()) then raise exception 'permission denied'; end if; delete from public.contact_methods where contact_id=p_contact_id; insert into public.contact_methods(contact_id,method_type,value,is_primary) select p_contact_id,nullif(btrim(x->>'type'),''),nullif(btrim(x->>'value'),''),coalesce((x->>'is_primary')::boolean,false) from jsonb_array_elements(coalesce(p_methods,'[]')) x; end $$;

create function public.get_my_family() returns jsonb language sql security definer stable set search_path=public,pg_temp as $$ select jsonb_build_object('family',to_jsonb(f),'members',coalesce((select jsonb_agg(to_jsonb(fm) order by fm.first_name) from public.family_members fm where fm.family_id=f.id),'[]'::jsonb)) from public.families f where f.owner_account_id=public.require_personal_account() $$;
create function public.create_family(p_name text) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare v uuid; begin insert into public.families(owner_account_id,name) values(public.require_personal_account(),nullif(btrim(p_name),'')) returning id into v; return v; exception when unique_violation then raise exception 'family already exists'; end $$;
create function public.create_family_member(p_first_name text,p_relationship text,p_member_type text default 'person',p_last_name text default null,p_birth_date date default null,p_pet_species text default null,p_contact_id uuid default null) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare v_family uuid; v uuid; begin select id into v_family from public.families where owner_account_id=public.require_personal_account(); if v_family is null then raise exception 'family not found'; end if; if p_contact_id is not null and not exists(select 1 from public.contacts c where c.id=p_contact_id and c.owner_account_id=public.require_personal_account()) then raise exception 'invalid contact'; end if; insert into public.family_members(family_id,first_name,last_name,relationship,member_type,birth_date,pet_species,contact_id) values(v_family,nullif(btrim(p_first_name),''),nullif(btrim(p_last_name),''),nullif(btrim(p_relationship),''),p_member_type,p_birth_date,nullif(btrim(p_pet_species),''),p_contact_id) returning id into v; return v; end $$;
create function public.update_family_member(p_member_id uuid,p_first_name text,p_relationship text,p_member_type text,p_last_name text default null,p_birth_date date default null,p_pet_species text default null,p_contact_id uuid default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.family_members%rowtype; begin if p_contact_id is not null and not exists(select 1 from public.contacts c where c.id=p_contact_id and c.owner_account_id=public.require_personal_account()) then raise exception 'invalid contact'; end if; update public.family_members fm set first_name=nullif(btrim(p_first_name),''),last_name=nullif(btrim(p_last_name),''),relationship=nullif(btrim(p_relationship),''),member_type=p_member_type,birth_date=p_birth_date,pet_species=nullif(btrim(p_pet_species),''),contact_id=p_contact_id from public.families f where fm.id=p_member_id and f.id=fm.family_id and f.owner_account_id=public.require_personal_account() returning fm.* into v; if not found then raise exception 'permission denied'; end if; return to_jsonb(v); end $$;
create function public.delete_family_member(p_member_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ begin delete from public.family_members fm using public.families f where fm.id=p_member_id and f.id=fm.family_id and f.owner_account_id=public.require_personal_account(); if not found then raise exception 'permission denied'; end if; end $$;

create function public.normalize_interest_name(p_name text) returns text language sql immutable set search_path=public,pg_temp as $$ select lower(regexp_replace(replace(btrim(p_name),'-',' '),'\s+',' ','g')) $$;
create function public.get_interest_catalog() returns setof jsonb language sql security definer stable set search_path=public,pg_temp as $$ select jsonb_build_object('category_id',c.id,'category_name',c.name,'interest_id',i.id,'display_name',i.display_name) from public.interest_categories c join public.interests i on i.category_id=c.id where i.origin='catalog' and i.publication_status='published' and i.status='active' order by c.name,i.display_name $$;
create function public.get_my_interests() returns setof jsonb language sql security definer stable set search_path=public,pg_temp as $$ select jsonb_build_object('interest_id',i.id,'category_id',i.category_id,'display_name',i.display_name) from public.profile_interests pi join public.interests i on i.id=pi.interest_id where pi.profile_id=public.require_personal_profile() and i.status='active' order by i.display_name $$;
create function public.add_my_interest(p_category_id uuid,p_display_name text) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare v_profile uuid:=public.require_personal_profile(); v_normalized text:=public.normalize_interest_name(p_display_name); v_interest uuid; begin if v_normalized='' or not exists(select 1 from public.interest_categories where id=p_category_id) then raise exception 'invalid interest'; end if; perform pg_advisory_xact_lock(hashtext(v_normalized)); select id into v_interest from public.interests where normalized_name=v_normalized; if v_interest is null then insert into public.interests(category_id,display_name,normalized_name,origin,publication_status,created_by_profile_id) values(p_category_id,btrim(p_display_name),v_normalized,'personal','private',v_profile) returning id into v_interest; end if; insert into public.profile_interests(profile_id,interest_id) values(v_profile,v_interest) on conflict do nothing; return v_interest; end $$;
create function public.remove_my_interest(p_interest_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ begin delete from public.profile_interests where profile_id=public.require_personal_profile() and interest_id=p_interest_id; end $$;
create function public.submit_my_interest_category_proposal(p_proposed_name text,p_note text default null) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v_profile uuid:=public.require_personal_profile(); v_normalized text:=public.normalize_interest_name(p_proposed_name); begin if v_normalized='' or length(v_normalized)>100 or length(coalesce(p_note,''))>500 then raise exception 'invalid proposal'; end if; insert into public.interest_category_proposals(profile_id,proposed_name,normalized_name,note) values(v_profile,btrim(p_proposed_name),v_normalized,nullif(btrim(p_note),'')) on conflict(profile_id,normalized_name) do nothing; end $$;

create function public.create_area_invite(p_area_id uuid,p_invitee_email text,p_expires_at timestamptz default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v_token text:=encode(gen_random_bytes(32),'hex'); v public.area_invites%rowtype; begin perform public.require_area_manage(p_area_id); insert into public.area_invites(area_id,invitee_email,token_hash,invited_by_account_id,expires_at) values(p_area_id,lower(nullif(btrim(p_invitee_email),'')),encode(digest(v_token,'sha256'),'hex'),public.require_current_account(),p_expires_at) returning * into v; return jsonb_build_object('invite_id',v.id,'token',v_token,'expires_at',v.expires_at); end $$;
create function public.get_my_area_invites() returns setof jsonb language sql security definer stable set search_path=public,pg_temp as $$ select jsonb_build_object('invite_id',i.id,'area_id',i.area_id,'area_name',a.name,'status',i.status,'expires_at',i.expires_at) from public.area_invites i join public.areas a on a.id=i.area_id join auth.users u on u.id=auth.uid() where lower(i.invitee_email)=lower(coalesce(u.email,'')) and i.status='pending' and (i.expires_at is null or i.expires_at>now()) order by i.created_at desc $$;
create function public.get_area_invites(p_area_id uuid) returns setof jsonb language plpgsql security definer set search_path=public,pg_temp as $$ begin perform public.require_area_manage(p_area_id); return query select jsonb_build_object('id',i.id,'invitee_email',i.invitee_email,'status',i.status,'expires_at',i.expires_at,'created_at',i.created_at) from public.area_invites i where i.area_id=p_area_id order by i.created_at desc; end $$;
create function public.accept_area_invite(p_token text) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.area_invites%rowtype; v_profile uuid:=public.require_personal_profile(); v_email text; begin select lower(email) into v_email from auth.users where id=auth.uid(); select * into v from public.area_invites i where i.token_hash=encode(digest(p_token,'sha256'),'hex') for update; if not found or v.status<>'pending' or (v.expires_at is not null and v.expires_at<=now()) or lower(v.invitee_email)<>v_email then raise exception 'invalid invite'; end if; insert into public.area_memberships(area_id,profile_id,role,added_by_account_id) values(v.area_id,v_profile,'member',v.invited_by_account_id) on conflict do nothing; update public.area_invites set status='accepted',accepted_by_profile_id=v_profile,responded_at=now() where id=v.id; end $$;
create function public.decline_area_invite(p_token text) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.area_invites%rowtype; v_email text; begin perform public.require_personal_profile(); select lower(email) into v_email from auth.users where id=auth.uid(); select * into v from public.area_invites i where i.token_hash=encode(digest(p_token,'sha256'),'hex') for update; if not found or v.status<>'pending' or lower(v.invitee_email)<>v_email then raise exception 'invalid invite'; end if; update public.area_invites set status='declined',responded_at=now() where id=v.id; end $$;
-- Recipient-facing actions deliberately use the opaque invite id returned by
-- get_my_area_invites.  The recipient identity/email check remains server-side;
-- invite tokens are never returned to the browser after creation.
create function public.accept_my_area_invite(p_invite_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.area_invites%rowtype; v_profile uuid:=public.require_personal_profile(); v_email text; begin select lower(email) into v_email from auth.users where id=auth.uid(); select * into v from public.area_invites i where i.id=p_invite_id for update; if not found or v.status<>'pending' or (v.expires_at is not null and v.expires_at<=now()) or lower(v.invitee_email)<>v_email then raise exception 'invalid invite'; end if; insert into public.area_memberships(area_id,profile_id,role,added_by_account_id) values(v.area_id,v_profile,'member',v.invited_by_account_id) on conflict do nothing; update public.area_invites set status='accepted',accepted_by_profile_id=v_profile,responded_at=now() where id=v.id; end $$;
create function public.decline_my_area_invite(p_invite_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.area_invites%rowtype; v_email text; begin perform public.require_personal_profile(); select lower(email) into v_email from auth.users where id=auth.uid(); select * into v from public.area_invites i where i.id=p_invite_id for update; if not found or v.status<>'pending' or (v.expires_at is not null and v.expires_at<=now()) or lower(v.invitee_email)<>v_email then raise exception 'invalid invite'; end if; update public.area_invites set status='declined',responded_at=now() where id=v.id; end $$;
create function public.revoke_area_invite(p_invite_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v_area uuid; begin select area_id into v_area from public.area_invites where id=p_invite_id; perform public.require_area_manage(v_area); update public.area_invites set status='revoked',responded_at=now() where id=p_invite_id and status='pending'; end $$;

create function public.target_scope(p_target_type text,p_target_id uuid) returns table(owner_account_id uuid,area_id uuid,can_read boolean,can_write boolean) language plpgsql security definer stable set search_path=public,pg_temp as $$ declare v_owner uuid; v_area uuid; begin if p_target_type='activity' then select a.owner_account_id,a.area_id into v_owner,v_area from public.activities a where a.id=p_target_id; elsif p_target_type='event' then select e.owner_account_id,e.area_id into v_owner,v_area from public.events e where e.id=p_target_id; elsif p_target_type='deadline' then select d.owner_account_id,null into v_owner from public.deadlines d where d.id=p_target_id; else raise exception 'invalid target'; end if; if v_owner is null and v_area is null then raise exception 'target not found'; end if; return query select v_owner,v_area,(v_owner=public.current_account_id() or (v_area is not null and (public.is_area_owner(v_area) or public.is_area_member(v_area)))),(v_owner=public.current_account_id() or (v_area is not null and public.can_manage_area(v_area))); end $$;
create function public.can_access_attachment_path(p_path text,p_write boolean default false) returns boolean language plpgsql security definer stable set search_path=public,pg_temp as $$ declare v text[]:=string_to_array(p_path,'/'); v_account uuid:=public.current_account_id(); v_scope record; begin if array_length(v,1)<>5 or v[1]<>'attachments' or v[2]<>v_account::text or nullif(v[5],'') is null then return false; end if; select * into v_scope from public.target_scope(v[3],v[4]::uuid); return case when p_write then v_scope.can_write else v_scope.can_read end; exception when others then return false; end $$;
create function public.register_attachment(p_target_type text,p_target_id uuid,p_storage_path text,p_original_filename text,p_mime_type text,p_byte_size bigint) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare v record; v_id uuid; begin select * into v from public.target_scope(p_target_type,p_target_id); if not v.can_write or not public.can_access_attachment_path(p_storage_path,true) then raise exception 'permission denied'; end if; insert into public.attachments(owner_account_id,area_id,target_type,target_id,storage_path,original_filename,mime_type,byte_size,uploaded_by_account_id) values(v.owner_account_id,v.area_id,p_target_type,p_target_id,p_storage_path,nullif(btrim(p_original_filename),''),nullif(btrim(p_mime_type),''),p_byte_size,public.require_current_account()) returning id into v_id; return v_id; end $$;
create function public.get_attachments(p_target_type text,p_target_id uuid) returns setof jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v record; begin select * into v from public.target_scope(p_target_type,p_target_id); if not v.can_read then raise exception 'permission denied'; end if; return query select to_jsonb(a) from public.attachments a where a.target_type=p_target_type and a.target_id=p_target_id order by a.created_at; end $$;
create function public.delete_attachment(p_attachment_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.attachments%rowtype; s record; begin select * into v from public.attachments where id=p_attachment_id; select * into s from public.target_scope(v.target_type,v.target_id); if not s.can_write then raise exception 'permission denied'; end if; delete from public.attachments where id=p_attachment_id; end $$;

create function public.get_dashboard(p_from timestamptz default now(),p_to timestamptz default now()+interval '30 days') returns jsonb language plpgsql security definer stable set search_path=public,pg_temp as $$ begin return jsonb_build_object('activities',coalesce((select jsonb_agg(to_jsonb(x)) from public.activities x where (x.owner_account_id=public.current_account_id() or (x.area_id is not null and (public.is_area_owner(x.area_id) or public.is_area_member(x.area_id)))) and coalesce(x.due_at,x.starts_at) between p_from and p_to),'[]'::jsonb),'events',coalesce((select jsonb_agg(to_jsonb(e)) from public.events e where (e.owner_account_id=public.current_account_id() or (e.area_id is not null and (public.is_area_owner(e.area_id) or public.is_area_member(e.area_id)))) and e.starts_at between p_from and p_to),'[]'::jsonb),'deadlines',coalesce((select jsonb_agg(x) from public.get_deadline_occurrences(p_from::date,p_to::date) x),'[]'::jsonb)); end $$;
create function public.get_calendar_occurrences(p_from timestamptz,p_to timestamptz) returns setof jsonb language sql security definer stable set search_path=public,pg_temp as $$ select jsonb_build_object('kind','activity','id',a.id,'title',a.title,'starts_at',a.starts_at,'ends_at',a.due_at,'all_day',a.is_all_day,'area_id',a.area_id) from public.activities a where (a.owner_account_id=public.current_account_id() or (a.area_id is not null and (public.is_area_owner(a.area_id) or public.is_area_member(a.area_id)))) and coalesce(a.due_at,a.starts_at) between p_from and p_to union all select jsonb_build_object('kind','event','id',e.id,'title',e.title,'starts_at',e.starts_at,'ends_at',e.ends_at,'all_day',e.is_all_day,'area_id',e.area_id) from public.events e where (e.owner_account_id=public.current_account_id() or (e.area_id is not null and (public.is_area_owner(e.area_id) or public.is_area_member(e.area_id)))) and e.starts_at between p_from and p_to union all select jsonb_build_object('kind','deadline','deadline_id',x->>'deadline_id','title',x->>'title','due_on',x->>'occurrence_on','all_day',true) from public.get_deadline_occurrences(p_from::date,p_to::date) x $$;

-- Internal recurrence expansion. It generates virtual occurrences only inside the
-- requested, bounded window; no occurrence rows are persisted. Activity timezone
-- is honored. Events have no timezone/interval/weekday columns, so their current
-- model supports daily or weekly recurrence in UTC at interval 1.
create function public.expand_recurrence_occurrences(p_starts_at timestamptz,p_ends_at timestamptz,p_frequency text,p_interval smallint,p_weekdays smallint[],p_until date,p_timezone text,p_from timestamptz,p_to timestamptz) returns table(occurrence_starts_at timestamptz,occurrence_ends_at timestamptz) language plpgsql security definer stable set search_path=public,pg_temp as $$
declare v_start timestamptz:=p_starts_at; v_end timestamptz:=coalesce(p_ends_at,p_starts_at); v_frequency text:=nullif(lower(btrim(coalesce(p_frequency,''))), ''); v_interval integer:=greatest(coalesce(p_interval,1),1); v_timezone text:=coalesce(nullif(btrim(coalesce(p_timezone,'')),''),'UTC'); v_local_start timestamp; v_duration interval; v_weekdays smallint[]; v_candidate_date date; v_candidate_local timestamp; v_candidate_start timestamptz; v_candidate_end timestamptz;
begin
  if v_start is null then return; end if;
  if p_from is null or p_to is null or p_to<=p_from then raise exception 'invalid occurrence range'; end if;
  if p_to>p_from+interval '400 days' then raise exception 'occurrence range too large'; end if;
  v_duration:=greatest(v_end-v_start,interval '0');
  if v_frequency is null then
    if v_start<p_to and v_start+v_duration>p_from then occurrence_starts_at:=v_start; occurrence_ends_at:=v_start+v_duration; return next; end if;
    return;
  end if;
  if v_frequency not in ('daily','weekly') then raise exception 'unsupported recurrence frequency'; end if;
  v_local_start:=v_start at time zone v_timezone;
  v_weekdays:=coalesce(nullif(p_weekdays,'{}'::smallint[]),array[extract(isodow from v_local_start)::smallint]);
  for v_candidate_date in select d::date from generate_series((p_from at time zone v_timezone)::date-1,(p_to at time zone v_timezone)::date+1,interval '1 day') d loop
    if v_candidate_date<v_local_start::date or (p_until is not null and v_candidate_date>p_until) then continue; end if;
    if v_frequency='daily' and mod(v_candidate_date-v_local_start::date,v_interval)<>0 then continue; end if;
    if v_frequency='weekly' and (extract(isodow from v_candidate_date)::smallint<>all(v_weekdays) or mod((v_candidate_date-date_trunc('week',v_local_start)::date)/7,v_interval)<>0) then continue; end if;
    v_candidate_local:=v_candidate_date+v_local_start::time;
    v_candidate_start:=v_candidate_local at time zone v_timezone;
    v_candidate_end:=v_candidate_start+v_duration;
    if v_candidate_start<p_to and v_candidate_end>p_from then occurrence_starts_at:=v_candidate_start; occurrence_ends_at:=v_candidate_end; return next; end if;
  end loop;
end $$;

create or replace function public.get_dashboard(p_from timestamptz default now(),p_to timestamptz default now()+interval '30 days') returns jsonb language plpgsql security definer stable set search_path=public,pg_temp as $$
declare v_account uuid:=public.require_current_account();
begin
  if p_to<=p_from then raise exception 'invalid occurrence range'; end if;
  return jsonb_build_object(
    'activities',coalesce((select jsonb_agg(to_jsonb(a)||jsonb_build_object('kind','activity','activity_id',a.id,'occurrence_starts_at',o.occurrence_starts_at,'occurrence_ends_at',o.occurrence_ends_at) order by o.occurrence_starts_at) from public.activities a cross join lateral public.expand_recurrence_occurrences(coalesce(a.starts_at,a.due_at),a.due_at,a.recurrence_frequency,a.recurrence_interval,a.recurrence_weekdays,a.recurrence_until,a.recurrence_timezone,p_from,p_to) o where (a.owner_account_id=v_account or (a.area_id is not null and (public.is_area_owner(a.area_id) or public.is_area_member(a.area_id)))) and a.status<>'cancelled'),'[]'::jsonb),
    'events',coalesce((select jsonb_agg(to_jsonb(e)||jsonb_build_object('kind','event','event_id',e.id,'occurrence_starts_at',o.occurrence_starts_at,'occurrence_ends_at',o.occurrence_ends_at) order by o.occurrence_starts_at) from public.events e cross join lateral public.expand_recurrence_occurrences(e.starts_at,e.ends_at,e.recurrence_frequency,null,null,e.recurrence_until,null,p_from,p_to) o where (e.owner_account_id=v_account or (e.area_id is not null and (public.is_area_owner(e.area_id) or public.is_area_member(e.area_id)))) and e.status<>'cancelled'),'[]'::jsonb),
    'deadlines',coalesce((select jsonb_agg(x) from public.get_deadline_occurrences(p_from::date,(p_to-interval '1 microsecond')::date) x),'[]'::jsonb),
    'todos',coalesce((select jsonb_agg(to_jsonb(a)||jsonb_build_object('kind','activity','activity_id',a.id) order by a.created_at) from public.activities a where (a.owner_account_id=v_account or (a.area_id is not null and (public.is_area_owner(a.area_id) or public.is_area_member(a.area_id)))) and a.status='open' and a.starts_at is null and a.due_at is null),'[]'::jsonb)
  );
end $$;

create or replace function public.get_calendar_occurrences(p_from timestamptz,p_to timestamptz) returns setof jsonb language plpgsql security definer stable set search_path=public,pg_temp as $$
declare v_account uuid:=public.require_current_account();
begin
  if p_to<=p_from then raise exception 'invalid occurrence range'; end if;
  return query
    select jsonb_build_object('kind','activity','id',a.id,'activity_id',a.id,'title',a.title,'starts_at',o.occurrence_starts_at,'ends_at',o.occurrence_ends_at,'all_day',a.is_all_day,'area_id',a.area_id,'status',a.status)
    from public.activities a cross join lateral public.expand_recurrence_occurrences(coalesce(a.starts_at,a.due_at),a.due_at,a.recurrence_frequency,a.recurrence_interval,a.recurrence_weekdays,a.recurrence_until,a.recurrence_timezone,p_from,p_to) o
    where (a.owner_account_id=v_account or (a.area_id is not null and (public.is_area_owner(a.area_id) or public.is_area_member(a.area_id)))) and a.status<>'cancelled'
    union all
    select jsonb_build_object('kind','event','id',e.id,'event_id',e.id,'title',e.title,'starts_at',o.occurrence_starts_at,'ends_at',o.occurrence_ends_at,'all_day',e.is_all_day,'area_id',e.area_id,'status',e.status)
    from public.events e cross join lateral public.expand_recurrence_occurrences(e.starts_at,e.ends_at,e.recurrence_frequency,null,null,e.recurrence_until,null,p_from,p_to) o
    where (e.owner_account_id=v_account or (e.area_id is not null and (public.is_area_owner(e.area_id) or public.is_area_member(e.area_id)))) and e.status<>'cancelled'
    union all
    select jsonb_build_object('kind','deadline','deadline_id',x->>'deadline_id','title',x->>'title','due_on',x->>'occurrence_on','occurs_on',x->>'occurrence_on','all_day',true,'is_completed',coalesce((x->>'completed')::boolean,false))
    from public.get_deadline_occurrences(p_from::date,(p_to-interval '1 microsecond')::date) x;
end $$;

-- Client RPCs are the only authenticated public surface. Helper functions remain ungranted.
revoke all on all functions in schema public from public;
grant execute on function public.get_current_account(),public.get_my_profile(),public.update_my_profile(text,text,date,text),public.get_my_organization(),public.update_my_organization(text,text,text,text,text,text),public.create_area(text,text,text),public.get_my_areas(),public.get_area(uuid),public.update_area(uuid,text,text,text),public.delete_area(uuid),public.get_area_members(uuid),public.add_area_member(uuid,uuid,public.area_role),public.remove_area_member(uuid,uuid),public.create_activity(text,text,uuid,timestamptz,timestamptz,boolean,public.priority_level,jsonb,text),public.get_activity(uuid),public.get_visible_activities(),public.get_activity_assignees(uuid),public.update_activity(uuid,text,text,timestamptz,timestamptz,boolean,public.priority_level,jsonb,text),public.set_activity_status(uuid,public.activity_status),public.delete_activity(uuid),public.set_activity_assignees(uuid,uuid[]),public.create_event(text,timestamptz,timestamptz,text,uuid,boolean,text,jsonb),public.get_event(uuid),public.get_visible_events(),public.update_event(uuid,text,timestamptz,timestamptz,text,boolean,text,jsonb),public.delete_event(uuid),public.set_event_participants(uuid,uuid[]),public.get_event_participants(uuid),public.set_event_status(uuid,text),public.create_list(text,text,uuid),public.get_list(uuid),public.get_visible_lists(),public.update_list(uuid,text,text),public.delete_list(uuid),public.create_list_item(uuid,text,integer),public.update_list_item(uuid,text,integer,text),public.delete_list_item(uuid),public.create_deadline(text,text,date,smallint,smallint,text,uuid),public.get_deadline(uuid),public.get_my_deadlines(),public.update_deadline(uuid,text,text,date,smallint,smallint,text,uuid,text),public.delete_deadline(uuid),public.get_deadline_occurrences(date,date),public.complete_deadline_occurrence(uuid,date,boolean),public.create_contact(text,text,date),public.get_contact(uuid),public.get_my_contacts(),public.update_contact(uuid,text,text,date),public.delete_contact(uuid),public.get_dashboard(timestamptz,timestamptz),public.get_calendar_occurrences(timestamptz,timestamptz) to authenticated;
grant execute on function public.replace_contact_methods(uuid,jsonb),public.delete_contact(uuid),public.create_family(text),public.get_my_family(),public.create_family_member(text,text,text,text,date,text,uuid),public.update_family_member(uuid,text,text,text,text,date,text,uuid),public.delete_family_member(uuid),public.get_interest_catalog(),public.get_my_interests(),public.add_my_interest(uuid,text),public.remove_my_interest(uuid),public.submit_my_interest_category_proposal(text,text),public.create_area_invite(uuid,text,timestamptz),public.get_my_area_invites(),public.get_area_invites(uuid),public.accept_area_invite(text),public.decline_area_invite(text),public.accept_my_area_invite(uuid),public.decline_my_area_invite(uuid),public.revoke_area_invite(uuid),public.register_attachment(text,uuid,text,text,text,bigint),public.get_attachments(text,uuid),public.delete_attachment(uuid) to authenticated;
alter function public.get_current_account() owner to postgres;
alter function public.require_area_read(uuid) owner to postgres;
alter function public.require_area_manage(uuid) owner to postgres;
alter function public.target_scope(text,uuid) owner to postgres;
alter function public.can_access_attachment_path(text,boolean) owner to postgres;
do $$ declare r record; begin for r in select p.oid::regprocedure as signature from pg_proc p where p.pronamespace='public'::regnamespace loop execute format('alter function %s owner to postgres',r.signature); end loop; end $$;
commit;
