-- Minimal live patch mirrored in familarea_api.sql.  Apply only to FamilArea.
create or replace function public.accept_my_area_invite(p_invite_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.area_invites%rowtype; v_profile uuid:=public.require_personal_profile(); v_email text; begin select lower(email) into v_email from auth.users where id=auth.uid(); select * into v from public.area_invites i where i.id=p_invite_id for update; if not found or v.status<>'pending' or (v.expires_at is not null and v.expires_at<=now()) or lower(v.invitee_email)<>v_email then raise exception 'invalid invite'; end if; insert into public.area_memberships(area_id,profile_id,role,added_by_account_id) values(v.area_id,v_profile,'member',v.invited_by_account_id) on conflict do nothing; update public.area_invites set status='accepted',accepted_by_profile_id=v_profile,responded_at=now() where id=v.id; end $$;
create or replace function public.decline_my_area_invite(p_invite_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.area_invites%rowtype; v_email text; begin perform public.require_personal_profile(); select lower(email) into v_email from auth.users where id=auth.uid(); select * into v from public.area_invites i where i.id=p_invite_id for update; if not found or v.status<>'pending' or (v.expires_at is not null and v.expires_at<=now()) or lower(v.invitee_email)<>v_email then raise exception 'invalid invite'; end if; update public.area_invites set status='declined',responded_at=now() where id=v.id; end $$;
create or replace function public.can_access_attachment_path(p_path text,p_write boolean default false) returns boolean language plpgsql security definer stable set search_path=public,pg_temp as $$ declare v text[]:=string_to_array(p_path,'/'); v_account uuid:=public.current_account_id(); v_scope record; begin if array_length(v,1)<>5 or v[1]<>'attachments' or v[2]<>v_account::text or nullif(v[5],'') is null then return false; end if; select * into v_scope from public.target_scope(v[3],v[4]::uuid); return case when p_write then v_scope.can_write else v_scope.can_read end; exception when others then return false; end $$;
alter function public.accept_my_area_invite(uuid) owner to postgres;
alter function public.decline_my_area_invite(uuid) owner to postgres;
alter function public.can_access_attachment_path(text,boolean) owner to postgres;
revoke all on function public.accept_my_area_invite(uuid),public.decline_my_area_invite(uuid) from public;
grant execute on function public.accept_my_area_invite(uuid),public.decline_my_area_invite(uuid) to authenticated;
